version: "3"

services:
  db:
    container_name: gsp-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: gsp
      MYSQL_DATABASE: gsp
      MYSQL_USER: gsp
      MYSQL_PASSWORD: gsp
    ports:
    - 127.0.0.1:3306:3306
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata: ~
